---
- name: Install fail2ban
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - fail2ban

- name: Copy fail2ban sendxmpp action configuration
  ansible.builtin.copy:
    src: fail2ban-xmpp.conf
    dest: /etc/fail2ban/action.d/xmpp.conf
    owner: root
    group: root
    mode: 0600

- name: Copy fail2ban configuration
  ansible.builtin.template:
    src: fail2ban.j2
    dest: /etc/fail2ban/jail.local
    mode: 0640
  notify: Restart fail2ban
