---
- name: install iptables
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - iptables-persistent
  tags: iptables

- name: disable ipv6 globally
  lineinfile:
    line: 'net.ipv6.conf.all.disable_ipv6 = 1'
    state: present
    insertafter: EOF
    path: /etc/sysctl.conf
  notify: activate sysctl
  tags: iptables

- name: allow established and related connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  tags: iptables

- name: allow internal traffic
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
  tags: iptables

- name: allow SSH connections
  iptables:
    chain: INPUT
    ctstate: NEW
    protocol: tcp
    destination_port: "{{ ssh_port | default('22') }}"
    jump: ACCEPT
  tags: iptables

- name: allow http traffic
  iptables:
    chain: INPUT
    ctstate: NEW
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
  tags: iptables

- name: enable logging
  iptables:
    chain: INPUT
    jump: LOG
  tags: iptables

- name: set iptables default INPUT policy to DROP
  iptables:
    chain: INPUT
    policy: DROP
  tags: iptables

- name: set iptables default OUTPUT policy to ACCEPT
  iptables:
    chain: OUTPUT
    policy: ACCEPT
  tags: iptables

- name: set iptables default FORWARD policy to DROP
  iptables:
    chain: FORWARD
    policy: DROP
  tags: iptables
