---
- name: Install iptables
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - iptables-persistent

- name: Disable IPv6 globally
  lineinfile:
    line: 'net.ipv6.conf.all.disable_ipv6 = 1'
    state: present
    insertafter: EOF
    path: /etc/sysctl.conf
  notify: Activate sysctl

- name: Set basic iptables rules
  iptables_raw:
    name: default_rules
    weight: 10
    rules: |
      -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
      -A INPUT -i lo -j ACCEPT
      -A INPUT -p tcp -m state --state NEW -m tcp --dport {{ ssh_port | default('22') }} -j ACCEPT
      -P INPUT DROP
      -P FORWARD DROP
      -P OUTPUT ACCEPT

- name: Enable logging
  iptables_raw:
    name: enable_logging
    weight: 99
    rules: |
          -A INPUT ! -i lo -j LOG --log-prefix "DROP " --log-ip-options --log-tcp-options
          -A OUTPUT ! -o lo -j LOG --log-prefix "DROP " --log-ip-options --log-tcp-options
          -A FORWARD ! -i lo -j LOG --log-prefix "DROP " --log-ip-options --log-tcp-options
