---
- name: Install iptables
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - iptables-persistent

- name: iptables drop invalid
  ansible.builtin.iptables:
    chain: INPUT
    match: state
    ctstate: INVALID
    jump: DROP
    comment: drop invalid
    action: insert
    rule_num: 1
  notify: save iptables

- name: iptables drop new TCP packets without the SYN flag
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    syn: negate
    match: state
    ctstate: NEW
    jump: DROP
    comment: drop new TCP packets without the SYN flag
    action: insert
    rule_num: 2
  notify: save iptables

- name: iptables drop XMAS packets
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    tcp_flags:
      flags: ALL
      flags_set:
        - FIN
        - PSH
        - URG
    jump: LOG
    log_prefix: "DROPPED XMAS PACKET:"
    comment: drop XMAS packets
    action: insert
    rule_num: 3
  notify: save iptables

- name: iptables allow related and established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    comment: allow related and established connections
    action: insert
    rule_num: 4
  notify: save iptables

- name: iptables allow internal traffic
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
    comment: allow internal traffic
  notify: save iptables

- name: iptables allow SSH port
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    match: state
    ctstate: NEW
    jump: ACCEPT
    comment: allow SSH port
  notify: save iptables

- name: iptables allow ICMP ping
  ansible.builtin.iptables:
    chain: INPUT
    protocol: icmp
    icmp_type: 8
    jump: ACCEPT
    comment: allow ICMP ping
  notify: save iptables

- name: iptables set the policy for the INPUT chain to DROP
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP
  notify: save iptables

- name: iptables set the policy for the FORWARD chain to DROP
  ansible.builtin.iptables:
    chain: FORWARD
    policy: DROP
  notify: save iptables

- name: iptables set the policy for the OUTPUT chain to ACCEPT
  ansible.builtin.iptables:
    chain: OUTPUT
    policy: ACCEPT
  notify: save iptables
