---

- name: Import iptables tasks
  import_tasks: iptables.yml
  tags: iptables
  notify: save iptables

- name: Import fail2ban tasks
  import_tasks: fail2ban.yml
  tags: fail2ban

- name: Import ssh tasks
  import_tasks: ssh.yml
  tags: ssh
