---
- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Activate sysctl
  ansible.builtin.command: "sysctl -p /etc/sysctl.conf"

- name: save iptables
  ansible.builtin.command: netfilter-persistent save
